name: Generate documentation
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
      - name: Generate documentation
        run: sbt "doc"
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: target/scala-2.13/api
      - name: Update GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/scala-2.13/api
